# -*- coding: utf-8 -*-
"""Curated Danbooru-inspired general visual tags.

Only category-0-style visual vocabulary is included here. Artist, copyright,
character, meta, minor-coded and explicit sexual tags are intentionally excluded.
"""

from __future__ import annotations

from collections import OrderedDict


DANBOORU_GENERAL_TAG_ALIASES = OrderedDict(
    [
        ("赛璐璐上色", "cel shading"),
        ("厚涂绘画", "painterly impasto rendering"),
        ("水彩晕染", "watercolor wash"),
        ("铅笔素描", "pencil sketch"),
        ("黑白线稿", "monochrome line art"),
        ("单色插画", "monochrome illustration"),
        ("网点漫画", "halftone manga shading"),
        ("复古画风", "retro art style"),
        ("90年代动画风", "1990s anime style"),
        ("动画截图感", "anime screencap aesthetic"),
        ("概念艺术", "concept art"),
        ("角色设计稿", "character design sheet"),
        ("平涂上色", "flat color rendering"),
        ("粗线稿", "bold line art"),
        ("顶光", "overhead lighting"),
        ("底光", "underlighting"),
        ("聚光灯", "spotlight"),
        ("伦勃朗光", "Rembrandt lighting"),
        ("明暗对照", "chiaroscuro"),
        ("柔和阴影", "soft shadows"),
        ("硬阴影", "hard shadows"),
        ("彩色阴影", "colored shadows"),
        ("光斑", "dappled light"),
        ("漏光", "light leak"),
        ("泛光", "bloom lighting"),
        ("高键光", "high-key lighting"),
        ("低键光", "low-key lighting"),
        ("双色调", "duotone color scheme"),
        ("互补色", "complementary color scheme"),
        ("冷暖对比", "warm-cool color contrast"),
        ("蓝调时刻", "blue hour"),
        ("月光", "moonlight"),
        ("霓虹光", "neon lighting"),
        ("鱼眼镜头", "fisheye lens"),
        ("取景器视角", "viewfinder framing"),
        ("牛仔景别", "cowboy shot"),
        ("膝上裁切", "above-the-knee crop"),
        ("鸟瞰视角", "bird's-eye view"),
        ("虫视视角", "worm's-eye view"),
        ("俯视", "high-angle view"),
        ("仰视", "low-angle view"),
        ("侧面视角", "side view"),
        ("背面视角", "back view"),
        ("第一人称视角", "first-person perspective"),
        ("极端透视", "extreme perspective"),
        ("广角畸变", "wide-angle distortion"),
        ("对称构图", "symmetrical composition"),
        ("居中构图", "centered composition"),
        ("三分法构图", "rule-of-thirds composition"),
        ("对角线构图", "diagonal composition"),
        ("框中框", "frame-within-a-frame composition"),
        ("负空间", "negative space"),
        ("前景遮挡", "foreground occlusion"),
        ("景深虚化", "depth-of-field blur"),
        ("倾斜地平线", "tilted horizon"),
        ("全景建立镜头", "wide establishing shot"),
        ("面部聚焦", "face-focused composition"),
        ("手部聚焦", "hand-focused composition"),
        ("多视角展示", "multi-view presentation"),
        ("参考设定表", "reference sheet"),
        ("表情组", "expression sheet"),
        ("服装变体展示", "outfit variation sheet"),
        ("回头看", "looking back"),
        ("侧身站立", "sideways standing pose"),
        ("交叉双臂", "arms crossed"),
        ("双手叉腰", "hands on hips"),
        ("手插口袋", "hands in pockets"),
        ("扶帽檐", "touching the hat brim"),
        ("撩头发", "brushing hair aside"),
        ("伸手向前", "reaching forward"),
        ("奔跑", "running"),
        ("行走", "walking"),
        ("跳跃", "jumping"),
        ("蹲姿", "crouching pose"),
        ("坐姿", "seated pose"),
        ("倚靠", "leaning pose"),
        ("战斗姿态", "combat stance"),
        ("防御姿态", "defensive stance"),
        ("持武器", "holding a weapon"),
        ("挥手", "waving"),
        ("指向远方", "pointing into the distance"),
        ("仰望", "looking upward"),
        ("低头", "looking downward"),
        ("简单背景", "simple background"),
        ("白色背景", "white background"),
        ("黑色背景", "black background"),
        ("渐变背景", "gradient background"),
        ("图案背景", "patterned background"),
        ("网格背景", "grid background"),
        ("透明背景", "transparent background"),
        ("凌乱房间", "messy room"),
        ("客厅", "living room"),
        ("厨房", "kitchen"),
        ("浴室", "bathroom"),
        ("咖啡馆", "cafe"),
        ("便利店", "convenience store"),
        ("火车站", "train station"),
        ("地铁站", "subway station"),
        ("屋顶", "rooftop"),
        ("小巷", "alley"),
        ("城市街道", "city street"),
        ("森林", "forest"),
        ("海滩", "beach"),
        ("湖畔", "lakeside"),
        ("花田", "flower field"),
        ("废墟", "ruins"),
        ("工厂", "factory"),
        ("实验室", "laboratory"),
        ("宫殿", "palace"),
        ("神殿", "temple"),
        ("分层穿搭", "layered outfit"),
        ("宽松外套", "oversized jacket"),
        ("高领上衣", "turtleneck top"),
        ("无袖上衣", "sleeveless top"),
        ("长袖衬衫", "long-sleeved shirt"),
        ("连帽衫", "hoodie"),
        ("飞行夹克", "bomber jacket"),
        ("风衣", "trench coat"),
        ("西装", "suit"),
        ("礼服", "formal dress"),
        ("百褶裙", "pleated skirt"),
        ("长裙", "long skirt"),
        ("短裤", "shorts"),
        ("工装裤", "cargo pants"),
        ("过膝靴", "over-knee boots"),
        ("运动鞋", "sneakers"),
        ("手套", "gloves"),
        ("围巾", "scarf"),
        ("领带", "necktie"),
        ("腰带", "belt"),
        ("吊坠", "pendant"),
        ("耳环", "earrings"),
        ("发带", "headband"),
        ("发夹", "hair clip"),
        ("眼镜", "glasses"),
        ("护目镜", "goggles"),
        ("胶片颗粒", "film grain"),
        ("色差", "chromatic aberration"),
        ("VHS噪点", "VHS noise"),
        ("动态模糊", "motion blur"),
        ("镜头光晕", "lens flare"),
        ("粒子效果", "particle effects"),
        ("漂浮尘埃", "floating dust particles"),
        ("印刷网点", "print halftone texture"),
        ("纸张纹理", "paper texture"),
        ("干净线条", "clean linework"),
    ]
)


DANBOORU_GENERAL_TAG_EXTENSIONS = OrderedDict(
    [
        (("画面风格", "艺术风格"), ["赛璐璐上色", "厚涂绘画", "水彩晕染", "铅笔素描", "黑白线稿", "单色插画", "网点漫画", "复古画风", "90年代动画风", "动画截图感", "概念艺术", "角色设计稿", "平涂上色", "粗线稿"]),
        (("光影氛围", "光线类型"), ["顶光", "底光", "聚光灯", "伦勃朗光", "柔和阴影", "硬阴影", "彩色阴影", "光斑", "漏光", "泛光", "高键光", "低键光", "月光", "霓虹光"]),
        (("光影氛围", "色调氛围"), ["明暗对照", "双色调", "互补色", "冷暖对比", "蓝调时刻"]),
        (("构图视角", "景别"), ["牛仔景别", "膝上裁切", "全景建立镜头"]),
        (("构图视角", "角度"), ["鸟瞰视角", "虫视视角", "俯视", "仰视", "侧面视角", "背面视角", "第一人称视角"]),
        (("构图视角", "镜头"), ["鱼眼镜头", "取景器视角", "极端透视", "广角畸变", "景深虚化"]),
        (("构图视角", "构图方式"), ["对称构图", "居中构图", "三分法构图", "对角线构图", "框中框", "负空间", "前景遮挡", "倾斜地平线"]),
        (("构图视角", "人像构图控制"), ["面部聚焦", "手部聚焦", "多视角展示", "参考设定表", "表情组", "服装变体展示"]),
        (("动作姿态", "半身动作"), ["回头看", "交叉双臂", "双手叉腰", "手插口袋", "扶帽檐", "撩头发", "伸手向前", "挥手", "指向远方", "仰望", "低头"]),
        (("动作姿态", "全身动作"), ["侧身站立", "奔跑", "行走", "跳跃", "蹲姿", "坐姿", "倚靠", "战斗姿态", "防御姿态", "持武器"]),
        (("服装造型", "现代细分"), ["分层穿搭", "宽松外套", "高领上衣", "无袖上衣", "长袖衬衫", "连帽衫", "飞行夹克", "风衣", "西装", "礼服", "百褶裙", "长裙", "短裤", "工装裤", "过膝靴", "运动鞋"]),
        (("服装造型", "配饰"), ["手套", "围巾", "领带", "腰带", "吊坠", "耳环", "发带", "发夹", "眼镜", "护目镜"]),
        (("场景背景", "室内场景"), ["简单背景", "白色背景", "黑色背景", "渐变背景", "图案背景", "网格背景", "透明背景", "凌乱房间", "客厅", "厨房", "浴室", "咖啡馆", "便利店", "实验室", "宫殿", "神殿"]),
        (("场景背景", "室外场景"), ["火车站", "地铁站", "屋顶", "小巷", "城市街道", "森林", "海滩", "湖畔", "花田", "废墟", "工厂"]),
        (("技术画质", "特效"), ["色差", "VHS噪点", "动态模糊", "镜头光晕", "粒子效果", "漂浮尘埃"]),
        (("技术画质", "画质描述"), ["胶片颗粒"]),
        (("技术画质", "画质描述"), ["印刷网点", "纸张纹理", "干净线条"]),
    ]
)


DANBOORU_VISUAL_INTENT_FAMILIES = (
    {"name": "背景形式", "max_keep": 1, "tags": ("简单背景", "白色背景", "黑色背景", "渐变背景", "图案背景", "网格背景", "透明背景")},
    {"name": "主视点", "max_keep": 1, "tags": ("鸟瞰视角", "虫视视角", "俯视", "仰视", "侧面视角", "背面视角", "第一人称视角")},
    {"name": "主景别", "max_keep": 1, "tags": ("面部聚焦", "手部聚焦", "牛仔景别", "膝上裁切", "全景建立镜头")},
    {"name": "色彩方案", "max_keep": 1, "tags": ("单色插画", "双色调", "互补色", "冷暖对比")},
    {"name": "主体动作", "max_keep": 1, "tags": ("奔跑", "行走", "跳跃", "蹲姿", "坐姿", "倚靠", "战斗姿态", "防御姿态")},
    {"name": "主光方向", "max_keep": 2, "tags": ("顶光", "底光", "聚光灯", "伦勃朗光", "高键光", "低键光", "月光", "霓虹光")},
)


DANBOORU_REFERENCE_SHEET_TAGS = frozenset({"参考设定表", "多视角展示"})
DANBOORU_REFERENCE_SHEET_BACKGROUND_TAGS = frozenset(
    {"简单背景", "白色背景", "黑色背景", "渐变背景", "网格背景", "透明背景"}
)
DANBOORU_REFERENCE_SHEET_DYNAMIC_TAGS = frozenset(
    {"鱼眼镜头", "第一人称视角", "极端透视", "广角畸变", "前景遮挡", "景深虚化", "倾斜地平线", "全景建立镜头"}
)
