# -*- coding: utf-8 -*-
"""Shared fantasy template, theme-pool, and translation profiles."""

from __future__ import annotations

from typing import Any


FANTASY_TEMPLATE_BASE_MAP = {
    "奇幻风格": "神话感",
    "西方奇幻": "神话感",
    "高等奇幻": "神话感",
    "剑与魔法": "神话感",
    "哥特奇幻": "神话感",
    "黑暗童话": "神话感",
    "精灵幻想": "神话感",
    "梦幻奇境": "神话感",
    "日式奇幻动画": "插画感",
    "漆原智志画风": "插画感",
    "结城信辉画风": "插画感",
    "童话绘本": "插画感",
    "魔幻油画": "插画感",
    "奇幻概念设计": "CG感",
    "史诗奇幻海报": "CG感",
}
FANTASY_TEMPLATE_OPTIONS = tuple(FANTASY_TEMPLATE_BASE_MAP)

FANTASY_THEME_POOL_OPTIONS = (
    "奇幻风格",
    "高等奇幻",
    "剑与魔法",
    "精灵秘境",
    "龙骑士史诗",
    "魔法学院",
    "地下城冒险",
    "黑暗童话",
    "哥特奇幻",
    "天使与恶魔",
    "魔女秘仪",
    "浮空城邦",
    "幻想宫廷",
    "冰雪王国",
    "沙漠神话",
    "海洋奇幻",
    "森林精灵",
    "蒸汽魔法",
    "异世界冒险",
    "日式奇幻OVA",
    "漆原智志幻想",
    "结城信辉幻想",
    "史诗群像",
    "远古遗迹",
    "龙与宝藏",
)


def _variant(style: str, variant_id: str, *tags: tuple[str, str]) -> dict[str, Any]:
    return {"id": variant_id, "style": style, "tags": list(tags)}


FANTASY_THEME_VARIANTS: dict[str, list[dict[str, Any]]] = {
    "奇幻风格": [
        _variant("高等奇幻", "elven-sky-city", ("奇幻风格", "画面风格"), ("精灵游侠", "主体"), ("浮空城", "场景背景"), ("魔法粒子", "技术画质")),
        _variant("奇幻概念设计", "dragon-ruins", ("奇幻概念设计", "画面风格"), ("龙骑士", "主体"), ("远古遗迹", "场景背景"), ("风暴天光", "光影氛围")),
    ],
    "高等奇幻": [
        _variant("高等奇幻", "royal-city", ("高等奇幻", "画面风格"), ("宫廷魔法师", "主体"), ("精灵王都", "场景背景"), ("金色晨辉", "光影氛围")),
        _variant("高等奇幻", "sacred-quest", ("高等奇幻", "画面风格"), ("圣骑士", "主体"), ("云端阶梯", "场景背景"), ("星辉权杖", "道具世界观")),
    ],
    "剑与魔法": [
        _variant("剑与魔法", "dungeon-party", ("剑与魔法", "画面风格"), ("女冒险者", "主体"), ("地下城遗迹", "场景背景"), ("魔剑", "道具世界观")),
        _variant("剑与魔法", "frontier-battle", ("剑与魔法", "画面风格"), ("魔剑士", "主体"), ("边境要塞", "场景背景"), ("火炬暖光", "光影氛围")),
    ],
    "精灵秘境": [
        _variant("精灵幻想", "sacred-tree", ("精灵幻想", "画面风格"), ("银发精灵", "主体"), ("精灵圣树", "场景背景"), ("翡翠森林光", "光影氛围")),
        _variant("结城信辉画风", "forest-temple", ("结城信辉画风", "画面风格"), ("精灵游侠", "主体"), ("森林神殿", "场景背景"), ("精灵长弓", "道具世界观")),
    ],
    "龙骑士史诗": [
        _variant("史诗奇幻海报", "sky-citadel", ("龙骑士史诗", "画面风格"), ("龙骑士", "主体"), ("天空堡垒", "场景背景"), ("龙枪", "道具世界观")),
        _variant("高等奇幻", "storm-flight", ("高等奇幻", "画面风格"), ("龙语者", "主体"), ("云海战场", "场景背景"), ("龙焰逆光", "光影氛围")),
    ],
    "魔法学院": [
        _variant("日式奇幻动画", "arcane-library", ("日式奇幻动画", "画面风格"), ("魔法学院学生", "主体"), ("奥术图书馆", "场景背景"), ("魔法书", "道具世界观")),
        _variant("奇幻概念设计", "spell-class", ("奇幻概念设计", "画面风格"), ("宫廷魔法师", "主体"), ("魔法学院", "场景背景"), ("魔法阵", "道具世界观")),
    ],
    "地下城冒险": [
        _variant("剑与魔法", "torch-corridor", ("地下城冒险", "画面风格"), ("女冒险者", "主体"), ("地下城遗迹", "场景背景"), ("火炬光", "光影氛围")),
        _variant("奇幻概念设计", "crystal-cavern", ("奇幻概念设计", "画面风格"), ("遗迹探险家", "主体"), ("水晶洞窟", "场景背景"), ("浮空水晶", "道具世界观")),
    ],
    "黑暗童话": [
        _variant("黑暗童话", "thorn-castle", ("黑暗童话", "画面风格"), ("黑暗女巫", "主体"), ("荆棘城堡", "场景背景"), ("冷月光", "光影氛围")),
        _variant("童话绘本", "haunted-forest", ("黑暗童话", "画面风格"), ("迷雾森林", "场景背景"), ("黑玫瑰", "道具世界观"), ("星尘辉光", "技术画质")),
    ],
    "哥特奇幻": [
        _variant("哥特奇幻", "cathedral", ("哥特奇幻", "画面风格"), ("战斗修女", "主体"), ("哥特教堂", "场景背景"), ("彩窗圣光", "光影氛围")),
        _variant("魔幻油画", "cursed-court", ("魔幻油画", "画面风格"), ("黑暗女王", "主体"), ("乌鸦古堡", "场景背景"), ("烛火", "光影氛围")),
    ],
    "天使与恶魔": [
        _variant("高等奇幻", "fallen-angel", ("高等奇幻", "画面风格"), ("堕落天使", "主体"), ("天穹遗迹", "场景背景"), ("黑色羽翼", "服装造型")),
        _variant("史诗奇幻海报", "holy-duel", ("史诗奇幻海报", "画面风格"), ("炎魔天使", "主体"), ("云海战场", "场景背景"), ("圣辉逆光", "光影氛围")),
    ],
    "魔女秘仪": [
        _variant("哥特奇幻", "moon-ritual", ("哥特奇幻", "画面风格"), ("黑暗女巫", "主体"), ("秘仪大厅", "场景背景"), ("魔法书", "道具世界观")),
        _variant("黑暗童话", "forest-coven", ("黑暗童话", "画面风格"), ("魔女", "主体"), ("月夜森林", "场景背景"), ("魔法阵", "道具世界观")),
    ],
    "浮空城邦": [
        _variant("奇幻概念设计", "sky-city", ("奇幻概念设计", "画面风格"), ("浮空城", "场景背景"), ("云海", "场景背景"), ("飞空艇", "道具世界观")),
        _variant("高等奇幻", "cloud-palace", ("高等奇幻", "画面风格"), ("天空宫殿", "场景背景"), ("金色晨辉", "光影氛围"), ("星图仪", "道具世界观")),
    ],
    "幻想宫廷": [
        _variant("幻想宫廷", "crystal-palace", ("幻想宫廷", "画面风格"), ("公主", "主体"), ("水晶宫殿", "场景背景"), ("水晶折射光", "光影氛围")),
        _variant("魔幻油画", "royal-banquet", ("魔幻油画", "画面风格"), ("宫廷魔法师", "主体"), ("幻想宴会厅", "场景背景"), ("伦勃朗光", "光影氛围")),
    ],
    "冰雪王国": [
        _variant("高等奇幻", "ice-palace", ("冰雪奇幻", "画面风格"), ("冰雪女王", "主体"), ("冰雪王宫", "场景背景"), ("冰晶权杖", "道具世界观")),
        _variant("奇幻概念设计", "frozen-frontier", ("奇幻概念设计", "画面风格"), ("冰霜骑士", "主体"), ("冰封要塞", "场景背景"), ("冷冽神性", "光影氛围")),
    ],
    "沙漠神话": [
        _variant("高等奇幻", "sun-temple", ("沙漠神话", "画面风格"), ("海市蜃楼神殿", "场景背景"), ("日轮", "道具世界观"), ("金色晨辉", "光影氛围")),
        _variant("魔幻油画", "desert-oracle", ("魔幻油画", "画面风格"), ("沙漠祭司", "主体"), ("沙漠神庙", "场景背景"), ("星图仪", "道具世界观")),
    ],
    "海洋奇幻": [
        _variant("梦幻奇境", "underwater-palace", ("海洋奇幻", "画面风格"), ("海洋祭司", "主体"), ("海底王国", "场景背景"), ("水下焦散", "光影氛围")),
        _variant("奇幻概念设计", "storm-coast", ("奇幻概念设计", "画面风格"), ("潮汐法师", "主体"), ("风暴海岸", "场景背景"), ("水晶法杖", "道具世界观")),
    ],
    "森林精灵": [
        _variant("精灵幻想", "ranger", ("精灵幻想", "画面风格"), ("精灵游侠", "主体"), ("远古森林", "场景背景"), ("精灵长弓", "道具世界观")),
        _variant("结城信辉画风", "bard", ("结城信辉画风", "画面风格"), ("精灵吟游诗人", "主体"), ("精灵圣树", "场景背景"), ("柔和赛璐璐", "技术画质")),
    ],
    "蒸汽魔法": [
        _variant("奇幻概念设计", "clockwork-city", ("蒸汽魔法", "画面风格"), ("机械魔导师", "主体"), ("蒸汽魔法都市", "场景背景"), ("魔导机械", "道具世界观")),
        _variant("史诗奇幻海报", "airship-dock", ("史诗奇幻海报", "画面风格"), ("飞空艇港", "场景背景"), ("锤纹黄铜", "技术画质"), ("暖色轮廓逆光", "光影氛围")),
    ],
    "异世界冒险": [
        _variant("日式奇幻动画", "market", ("日式奇幻动画", "画面风格"), ("女冒险者", "主体"), ("异世界城镇", "场景背景"), ("冒险地图", "道具世界观")),
        _variant("剑与魔法", "portal", ("剑与魔法", "画面风格"), ("传送门", "道具世界观"), ("边境村庄", "场景背景"), ("清晨柔光", "光影氛围")),
    ],
    "日式奇幻OVA": [
        _variant("日式奇幻动画", "cel-quest", ("日式奇幻动画", "画面风格"), ("90年代奇幻OVA质感", "技术画质"), ("森林遗迹", "场景背景"), ("赛璐璐高光", "技术画质")),
        _variant("漆原智志画风", "heroine", ("漆原智志画风", "画面风格"), ("幻想女战士", "主体"), ("水晶宫殿", "场景背景"), ("宝石色调上色", "技术画质")),
    ],
    "漆原智志幻想": [
        _variant("漆原智志画风", "jewel-warrior", ("漆原智志画风", "画面风格"), ("幻想女战士", "主体"), ("龙鳞铠甲", "服装造型"), ("宝石色调上色", "技术画质")),
        _variant("漆原智志画风", "crystal-palace", ("漆原智志画风", "画面风格"), ("华丽奇幻角色设计", "技术画质"), ("水晶宫殿", "场景背景"), ("锐利高光", "光影氛围")),
    ],
    "结城信辉幻想": [
        _variant("结城信辉画风", "elf-hero", ("结城信辉画风", "画面风格"), ("精灵游侠", "主体"), ("优雅奇幻线稿", "技术画质"), ("远古森林", "场景背景")),
        _variant("结城信辉画风", "ensemble", ("结城信辉画风", "画面风格"), ("冒险队群像", "构图视角"), ("天空堡垒", "场景背景"), ("柔和赛璐璐", "技术画质")),
    ],
    "史诗群像": [
        _variant("史诗奇幻海报", "hero-party", ("史诗群像", "画面风格"), ("冒险队群像", "构图视角"), ("战场", "场景背景"), ("英雄海报构图", "构图视角")),
        _variant("高等奇幻", "royal-alliance", ("高等奇幻", "画面风格"), ("多阵营联盟", "主体"), ("精灵王都", "场景背景"), ("旗帜", "道具世界观")),
    ],
    "远古遗迹": [
        _variant("奇幻概念设计", "ruin-explorer", ("奇幻概念设计", "画面风格"), ("遗迹探险家", "主体"), ("远古遗迹", "场景背景"), ("神谕石碑", "道具世界观")),
        _variant("魔幻油画", "forgotten-temple", ("魔幻油画", "画面风格"), ("遗忘神殿", "场景背景"), ("云隙光", "光影氛围"), ("浮空水晶", "道具世界观")),
    ],
    "龙与宝藏": [
        _variant("剑与魔法", "treasure-hall", ("剑与魔法", "画面风格"), ("龙语者", "主体"), ("龙巢宝库", "场景背景"), ("魔剑", "道具世界观")),
        _variant("史诗奇幻海报", "dragon-awakening", ("史诗奇幻海报", "画面风格"), ("巨龙俯瞰", "构图视角"), ("龙蛋", "道具世界观"), ("龙焰火星", "技术画质")),
    ],
}

FANTASY_TEMPLATE_STYLE_VARIANTS: dict[str, list[dict[str, Any]]] = {
    "奇幻风格": [
        {"id": "high", "tags": [("奇幻风格", "画面风格"), ("高等奇幻", "画面风格"), ("精灵王都", "场景背景"), ("金色晨辉", "光影氛围")]},
        {"id": "dream", "tags": [("奇幻风格", "画面风格"), ("梦幻奇境", "画面风格"), ("水晶湖", "场景背景"), ("星尘辉光", "技术画质")]},
    ],
    "西方奇幻": [
        {"id": "knight", "tags": [("西方奇幻", "画面风格"), ("剑与魔法", "画面风格"), ("石砌城堡", "场景背景"), ("火炬暖光", "光影氛围")]},
        {"id": "elf", "tags": [("西方奇幻", "画面风格"), ("精灵幻想", "画面风格"), ("远古森林", "场景背景"), ("翡翠森林光", "光影氛围")]},
    ],
    "高等奇幻": [
        {"id": "court", "tags": [("高等奇幻", "画面风格"), ("幻想宫廷", "画面风格"), ("水晶宫殿", "场景背景"), ("圣辉逆光", "光影氛围")]},
        {"id": "epic", "tags": [("高等奇幻", "画面风格"), ("史诗奇幻海报", "画面风格"), ("浮空城", "场景背景"), ("风暴天光", "光影氛围")]},
    ],
    "剑与魔法": [
        {"id": "dungeon", "tags": [("剑与魔法", "画面风格"), ("地下城冒险", "画面风格"), ("地下城遗迹", "场景背景"), ("火炬光", "光影氛围")]},
        {"id": "dragon", "tags": [("剑与魔法", "画面风格"), ("龙骑士史诗", "画面风格"), ("龙巢宝库", "场景背景"), ("龙焰逆光", "光影氛围")]},
    ],
    "哥特奇幻": [
        {"id": "cathedral", "tags": [("哥特奇幻", "画面风格"), ("哥特教堂", "场景背景"), ("彩窗圣光", "光影氛围"), ("哥特礼服", "服装造型")]},
        {"id": "castle", "tags": [("哥特奇幻", "画面风格"), ("黑暗童话", "画面风格"), ("乌鸦古堡", "场景背景"), ("冷月光", "光影氛围")]},
    ],
    "黑暗童话": [
        {"id": "thorn", "tags": [("黑暗童话", "画面风格"), ("荆棘城堡", "场景背景"), ("黑玫瑰", "道具世界观"), ("月光", "光影氛围")]},
        {"id": "forest", "tags": [("黑暗童话", "画面风格"), ("童话绘本", "画面风格"), ("迷雾森林", "场景背景"), ("柔和光晕", "技术画质")]},
    ],
    "精灵幻想": [
        {"id": "forest", "tags": [("精灵幻想", "画面风格"), ("精灵圣树", "场景背景"), ("叶隙斑驳光", "光影氛围"), ("精灵轻甲", "服装造型")]},
        {"id": "starlight", "tags": [("精灵幻想", "画面风格"), ("远古森林", "场景背景"), ("星辉月光", "光影氛围"), ("水晶法杖", "道具世界观")]},
    ],
    "梦幻奇境": [
        {"id": "garden", "tags": [("梦幻奇境", "画面风格"), ("浮空花园", "场景背景"), ("柔和光晕", "技术画质"), ("魔法粒子", "技术画质")]},
        {"id": "lake", "tags": [("梦幻奇境", "画面风格"), ("水晶湖", "场景背景"), ("水晶折射光", "光影氛围"), ("星尘辉光", "技术画质")]},
    ],
    "日式奇幻动画": [
        {"id": "cel", "tags": [("日式奇幻动画", "画面风格"), ("精细赛璐璐", "技术画质"), ("魔法学院", "场景背景"), ("赛璐璐高光", "技术画质")]},
        {"id": "ova", "tags": [("日式奇幻动画", "画面风格"), ("90年代奇幻OVA质感", "技术画质"), ("异世界城镇", "场景背景"), ("黄昏逆光", "光影氛围")]},
    ],
    "漆原智志画风": [
        {"id": "jewel-cel", "tags": [("漆原智志画风", "画面风格"), ("日式奇幻动画", "画面风格"), ("华丽奇幻角色设计", "技术画质"), ("宝石色调上色", "技术画质")]},
        {"id": "heroic", "tags": [("漆原智志画风", "画面风格"), ("90年代奇幻OVA质感", "技术画质"), ("龙鳞铠甲", "服装造型"), ("龙焰火星", "技术画质")]},
    ],
    "结城信辉画风": [
        {"id": "elegant-line", "tags": [("结城信辉画风", "画面风格"), ("优雅奇幻线稿", "技术画质"), ("精灵幻想", "画面风格"), ("柔和赛璐璐", "技术画质")]},
        {"id": "ensemble", "tags": [("结城信辉画风", "画面风格"), ("高等奇幻", "画面风格"), ("冒险队群像", "构图视角"), ("星辉月光", "光影氛围")]},
    ],
    "童话绘本": [
        {"id": "watercolor", "tags": [("童话绘本", "画面风格"), ("水彩晕染", "技术画质"), ("精灵圣树", "场景背景"), ("柔和色彩", "光影氛围")]},
        {"id": "gouache", "tags": [("童话绘本", "画面风格"), ("水粉插画", "画面风格"), ("奇幻集市", "场景背景"), ("暖色灯光", "光影氛围")]},
    ],
    "魔幻油画": [
        {"id": "baroque", "tags": [("魔幻油画", "画面风格"), ("巴洛克", "画面风格"), ("幻想宫廷", "画面风格"), ("伦勃朗光", "光影氛围")]},
        {"id": "romantic", "tags": [("魔幻油画", "画面风格"), ("浪漫主义油画", "画面风格"), ("远古遗迹", "场景背景"), ("暮色天光", "光影氛围")]},
    ],
    "奇幻概念设计": [
        {"id": "environment", "tags": [("奇幻概念设计", "画面风格"), ("史诗概念艺术完成度", "技术画质"), ("浮空城", "场景背景"), ("体积光", "光影氛围")]},
        {"id": "character", "tags": [("奇幻概念设计", "画面风格"), ("奇幻角色设定", "画面风格"), ("魔法学院制服", "服装造型"), ("参考设定表", "构图视角")]},
    ],
    "史诗奇幻海报": [
        {"id": "hero", "tags": [("史诗奇幻海报", "画面风格"), ("英雄海报构图", "构图视角"), ("龙骑士", "主体"), ("风暴天光", "光影氛围")]},
        {"id": "ensemble", "tags": [("史诗奇幻海报", "画面风格"), ("史诗群像", "画面风格"), ("冒险队群像", "构图视角"), ("日落逆光", "光影氛围")]},
    ],
}

FANTASY_STYLE_LEAD_ZH = {
    "奇幻风格": "高完成度奇幻主视觉",
    "西方奇幻": "西方奇幻史诗插画",
    "高等奇幻": "高等奇幻史诗主视觉",
    "剑与魔法": "剑与魔法冒险插画",
    "哥特奇幻": "哥特奇幻叙事插画",
    "黑暗童话": "黑暗童话绘本主视觉",
    "精灵幻想": "精灵幻想角色插画",
    "梦幻奇境": "梦幻奇境插画",
    "日式奇幻动画": "日式奇幻动画定帧",
    "漆原智志画风": "漆原智志式华丽奇幻动画插画",
    "结城信辉画风": "结城信辉式优雅奇幻角色插画",
    "童话绘本": "奇幻童话绘本插画",
    "魔幻油画": "魔幻叙事油画",
    "奇幻概念设计": "高完成度奇幻概念设计",
    "史诗奇幻海报": "史诗奇幻电影海报",
}
FANTASY_STYLE_LEAD_EN = {
    "奇幻风格": "highly finished fantasy key visual",
    "西方奇幻": "western fantasy epic illustration",
    "高等奇幻": "high fantasy epic key visual",
    "剑与魔法": "sword-and-sorcery adventure illustration",
    "哥特奇幻": "gothic fantasy narrative illustration",
    "黑暗童话": "dark fairy-tale storybook key visual",
    "精灵幻想": "elven fantasy character illustration",
    "梦幻奇境": "dreamlike fantasy wonderland illustration",
    "日式奇幻动画": "Japanese fantasy anime key frame",
    "漆原智志画风": "Satoshi Urushihara-inspired ornate fantasy anime illustration",
    "结城信辉画风": "Nobuteru Yuki-inspired elegant fantasy character illustration",
    "童话绘本": "fantasy fairy-tale storybook illustration",
    "魔幻油画": "magical narrative oil painting",
    "奇幻概念设计": "highly finished fantasy concept design",
    "史诗奇幻海报": "epic fantasy cinematic poster",
}

FANTASY_STYLE_TRANSLATIONS = {
    **FANTASY_STYLE_LEAD_EN,
    "奇幻风格": "fantasy style",
    "西方奇幻": "western fantasy",
    "高等奇幻": "high fantasy",
    "剑与魔法": "sword and sorcery",
    "哥特奇幻": "gothic fantasy",
    "黑暗童话": "dark fairy tale",
    "精灵幻想": "elven fantasy",
    "梦幻奇境": "dreamlike fantasy wonderland",
    "日式奇幻动画": "Japanese fantasy anime",
    "漆原智志画风": "Satoshi Urushihara style",
    "结城信辉画风": "Nobuteru Yuki style",
    "童话绘本": "fairy-tale storybook illustration",
    "魔幻油画": "magical fantasy oil painting",
    "奇幻概念设计": "fantasy concept design",
    "史诗奇幻海报": "epic fantasy poster",
    "幻想宫廷": "fantasy royal court",
    "地下城冒险": "dungeon adventure",
    "龙骑士史诗": "dragon-rider epic",
    "沙漠神话": "desert mythology",
    "海洋奇幻": "ocean fantasy",
    "蒸汽魔法": "steampunk magic",
    "史诗群像": "epic ensemble cast",
    "精灵游侠": "elven ranger",
    "龙骑士": "dragon rider",
    "魔法学院学生": "magic academy student",
    "宫廷魔法师": "royal court mage",
    "圣骑士": "holy knight",
    "魔剑士": "spellblade warrior",
    "龙语者": "dragon speaker",
    "遗迹探险家": "ancient-ruin explorer",
    "黑暗女巫": "dark witch",
    "黑暗女王": "dark queen",
    "沙漠祭司": "desert priestess",
    "海洋祭司": "ocean priestess",
    "潮汐法师": "tide mage",
    "精灵吟游诗人": "elven bard",
    "机械魔导师": "clockwork archmage",
    "幻想女战士": "fantasy female warrior",
    "多阵营联盟": "multi-faction alliance",
    "精灵王都": "elven capital",
    "浮空城": "floating city",
    "天空堡垒": "sky citadel",
    "云海战场": "battlefield above the clouds",
    "奥术图书馆": "arcane library",
    "魔法学院": "magic academy",
    "地下城遗迹": "ancient dungeon ruins",
    "水晶洞窟": "crystal cavern",
    "荆棘城堡": "thorn castle",
    "乌鸦古堡": "raven castle",
    "天穹遗迹": "celestial ruins",
    "秘仪大厅": "ritual hall",
    "天空宫殿": "palace in the sky",
    "水晶宫殿": "crystal palace",
    "幻想宴会厅": "fantasy banquet hall",
    "冰雪王宫": "ice palace",
    "冰封要塞": "frozen fortress",
    "海市蜃楼神殿": "mirage temple",
    "沙漠神庙": "desert temple",
    "海底王国": "underwater kingdom",
    "风暴海岸": "storm coast",
    "远古森林": "ancient forest",
    "精灵圣树": "sacred elven tree",
    "蒸汽魔法都市": "steampunk magic city",
    "飞空艇港": "airship harbor",
    "异世界城镇": "otherworld fantasy town",
    "边境村庄": "frontier village",
    "森林遗迹": "forest ruins",
    "奇幻集市": "fantasy market",
    "水晶湖": "crystal lake",
    "浮空花园": "floating garden",
    "石砌城堡": "stone castle",
    "边境要塞": "frontier fortress",
    "森林神殿": "forest temple",
    "龙巢宝库": "dragon treasure vault",
    "远古遗迹": "ancient ruins",
    "遗忘神殿": "forgotten temple",
    "水晶法杖": "crystal staff",
    "星辉权杖": "starlight scepter",
    "精灵长弓": "elven longbow",
    "龙枪": "dragon lance",
    "魔剑": "enchanted sword",
    "魔法书": "spellbook",
    "魔法阵": "magic circle",
    "浮空水晶": "floating crystals",
    "飞空艇": "airship",
    "星图仪": "celestial astrolabe",
    "冰晶权杖": "ice-crystal scepter",
    "魔导机械": "magitech machinery",
    "冒险地图": "adventure map",
    "传送门": "magic portal",
    "黑玫瑰": "black rose",
    "黑色羽翼": "black feathered wings",
    "龙蛋": "dragon egg",
    "旗帜": "battle banners",
    "魔法粒子": "magic particles",
    "星尘辉光": "stardust glow",
    "风暴天光": "storm-lit sky",
    "金色晨辉": "golden dawn light",
    "翡翠森林光": "emerald forest light",
    "龙焰逆光": "dragon-fire backlight",
    "火炬暖光": "warm torchlight",
    "火炬光": "torchlight",
    "彩窗圣光": "stained-glass sacred light",
    "星辉月光": "starlit moonlight",
    "水晶折射光": "refracted crystal light",
    "水下焦散": "underwater caustic light",
    "锐利高光": "crisp cel highlights",
    "暮色天光": "twilight sky light",
    "精灵轻甲": "elven light armor",
    "龙鳞铠甲": "dragon-scale armor",
    "魔法学院制服": "magic academy uniform",
    "哥特礼服": "gothic fantasy gown",
    "华丽奇幻角色设计": "ornate fantasy character design",
    "优雅奇幻线稿": "elegant fantasy linework",
    "宝石色调上色": "jewel-tone coloring",
    "精细赛璐璐": "refined cel shading",
    "柔和赛璐璐": "soft cel shading",
    "赛璐璐高光": "cel-shaded highlights",
    "90年代奇幻OVA质感": "1990s fantasy OVA aesthetic",
    "史诗概念艺术完成度": "epic concept-art finish",
    "奇幻角色设定": "fantasy character design sheet",
    "英雄海报构图": "heroic poster composition",
    "冒险队群像": "adventuring-party ensemble",
    "巨龙俯瞰": "dragon overhead composition",
    "龙焰火星": "dragon-fire sparks",
    "浪漫主义油画": "romantic fantasy oil painting",
}
FANTASY_STYLE_TRANSLATIONS.update({
    FANTASY_STYLE_LEAD_ZH[name]: FANTASY_STYLE_LEAD_EN[name]
    for name in FANTASY_STYLE_LEAD_ZH
})
